fix: update folder name to prevent conflict
ImportError: cannot import name 'Chzzk' from partially initialized module 'chzzk' (most likely due to a circular import)